package com.me.model;

public enum Strategy {
    FLAT_RED, FLAT_BLACK, FLAT_LOW, FLAT_HIGH, FLAT_EVEN, FLAT_ODD,
    COLOR_SAME, COLOR_INVERT, LOW_HIGH_SAME, LOW_HIGH_INVERT, EVEN_ODD_SAME, EVEN_ODD_INVERT,

    COLOR_HL_SAME, COLOR_HL_INVERT, COLOR_EO_SAME, COLOR_EO_INVERT, HL_EO_SAME, HL_EO_INVERT,
    COLOR_HL_CLR_INVERT, COLOR_HL_HL_INVERT, COLOR_EO_CLR_INVERT, COLOR_EO_EO_INVERT, HL_EO_HL_INVERT, HL_EO_EO_INVERT,

    COLOR_HL_EO_SAME, COLOR_HL_EO_INVERT,
    COLOR_HL_EO_CLR_INVERT, COLOR_HL_EO_HL_INVERT, COLOR_HL_EO_EO_INVERT,
    COLOR_HL_EO_CLR_SAME, COLOR_HL_EO_HL_SAME, COLOR_HL_EO_EO_SAME,

    GREEN_BLACK_ATTACK, JAMES_BOND;

}
